angular.module('MetronicApp').constant('CommonConstants', {
    "filters": {
        "AGENT_APPR_RPT": "AGENT_APPR_RPT",
        "MY_APPRAISALS": "MY_APPRAISALS",
        "UNDERWRITER_APPR_RPT": "UNDERWRITER_APPR_RPT",
        "UNDERWRITER_ALL_APPR_RPT": "UNDERWRITER_ALL_APPR_RPT",
        "AGENT_INVOICES": "AGENT_INVOICES",    
        "ADJUSTER_ALL_CLAIMS_RPT":"ADJUSTER_ALL_CLAIMS_RPT", 
        "CLAIM_RPT":"CLAIM_RPT",
        "SALVAGE_RPT":"SALVAGE_RPT",
        "SUPERVISOR_ALL_CLAIMS_RPT":"SUPERVISOR_ALL_CLAIMS_RPT",
        "INVOICE_BILLS_PAYMENTS":"INVOICE_BILLS_PAYMENTS",
        "INVOICE_PAYABLE":"INVOICE_PAYABLE",
        "CLAIM_MANGER_ALL_CLAIM_RPT":"CLAIM_MANGER_ALL_CLAIM_RPT",
        "INSURANCE_ACC_MANAGER_RPT":"INSURANCE_ACC_MANAGER_RPT"
    }
});