name: Update Configuration

on:
  push:
    branches:
      - sakha_master

jobs:
  update-configuration:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Replace values in the configuration.json file
        run: |
          # Read the content of the configuration.json file into a variable
          config=$(<Config/Configuration.json)
    
          # Replace values in the variable using string manipulation
          config=${config//\"insuranceCarrier\":\"The Evolution Insurance Company\"/\"insuranceCarrier\":\"Insurance Company Name\"}
          config=${config//\"serverAddress\": \"http://173.255.198.245:8080\"/\"serverAddress\": \"http://localhost:8080\"}
          config=${config//\"Xoriginator\": \"http://173.255.198.245:8080/evolution\"/\"Xoriginator\": \"worldwide.3circledemo.com\"}
          config=${config//\"apiurl\":\"/ArtigemRS-FI/api/\"/\"apiurl\":\"/ArtigemRS-FI/api/\"}
          config=${config//\"AdminApiurl\": \"/ArtigemRS-FI_Admin/api/\"/\"AdminApiurl\": \"/ArtigemRS-FI_Admin/api/\"}
          config=${config//\"receipturl\": \"/\"/\"receipturl\": \"/\"}
          config=${config//\"ClaimTemplate\":\"/ArtigemRS-FI/artigem/templates/ClaimDetails.xlsx\"/\"ClaimTemplate\":\"/ArtigemRS-FI/artigem/templates/ClaimDetails.xlsx\"}
          config=${config//\"ItemTemplate\": \"/ArtigemRS-FI/artigem/templates/postloss_Items.xlsx\"/\"ItemTemplate\": \"/ArtigemRS-FI/artigem/templates/postloss_Items.xlsx\"}
          config=${config//\"VendorDetailsTemplate\": \"/ArtigemRS-FI/artigem/templates/VendorCatalogUpload.xlsx\"/\"VendorDetailsTemplate\": \"/ArtigemRS-FI/artigem/templates/VendorCatalogUpload.xlsx\"}
          config=${config//\"UserDetailsTemplate\":\"/ArtigemRS-FI/artigem/templates/UserDetails.xlsx\"/\"UserDetailsTemplate\":\"/ArtigemRS-FI/artigem/templates/UserDetails.xlsx\"}
          config=${config//\"bestbuyUrl\": \"https://api.bestbuy.com/v1/products\"/\"bestbuyUrl\": \"https://api.bestbuy.com/v1/products\"}
          config=${config//\"claimProfile\": \"Contents\"/\"claimProfile\": \"Contents\"}
          config=${config//\"serviceRequests\": \"true\"/\"serviceRequests\": \"true\"}
          config=${config//\"jewelryVendor\": \"ARTGM\"/\"jewelryVendor\": \"ARTGM\"}
          config=${config//\"speedCheckVendor\": \"ARTGM\"/\"speedCheckVendor\": \"ARTGM\"}
          config=${config//\"hideCaptcha\": \"true\"/\"hideCaptcha\": \"true\"}
          config=${config//\"SpeedCheckApiurl\": \"http://173.255.198.245:8080/SpeedCheck_App/api/\"/\"SpeedCheckApiurl\": \"http://localhost:8080/SpeedCheck_App/api/\"}
          config=${config//\"gemGuideApi\": \"true\"/\"gemGuideApi\": \"true\"}
          config=${config//\"googleShoppingDropdown\": \"false\"/\"googleShoppingDropdown\": \"false\"}
          config=${config//\"ThirdPartyAdjusting\": \"true\"/\"ThirdPartyAdjusting\": \"true\"}
          config=${config//\"loginWithSSO\": \"false\"/\"loginWithSSO\": \"false\"}

          # Write the modified content back to the configuration.json file
          echo "$config" > Config/Configuration.json

      - name: Display changes
        run: cat Config/Configuration.json  # Display the modified configuration file

      - name: Save project code as artifact
        uses: actions/upload-artifact@v2
        with:
          name: evolution
          path: .  # Save the entire project code directory

      - name: Rename artifact directory
        run: |
          mv $GITHUB_WORKSPACE evolution-app  # Rename the artifact directory

      - name: Copy code to Tomcat
        run: |
          # Replace "/path/to/tomcat/webapps" with the actual path to your Tomcat's webapps directory
          cp -r evolution-app /opt/tomcat/webapps/

          
